import {StateSnapshot} from './state';
import {PoliticalState} from './politics';
export type EventChoice={id:string;label:string;text:string;state?:Partial<StateSnapshot>;politics?:{capital?:number;mandates?:number};memoryRequired?:string;followup?:string};
export type GameEvent={id:string;title:string;source:string;body:string;priority:number;minDay:number;maxDay?:number;once:true;condition:(s:StateSnapshot,p:PoliticalState,seen:string[])=>boolean;choices:EventChoice[]};
const has=(p:PoliticalState,id:string)=>p.memories.some(m=>m.id===id);
export const events:GameEvent[]=[
{id:'velmash-ultimatum',title:'Velmash nie wypłaci pensji',source:'MINISTERSTWO PRZEMYSŁU / DRAVINA',body:'Dyrekcja Velmashu informuje, że bez płynności do piątku zabraknie środków na wynagrodzenia. Federacja Metalowców przygotowuje zebrania zakładowe. Velić żąda telefonu bez świadków.',priority:90,minDay:2,once:true,condition:(s)=>s.production<76||s.regions.dravina.unrest>60,choices:[{id:'credit',label:'Uruchom kredyt pomostowy',text:'Kupujesz czas za pieniądze i inflację.',state:{treasury:-35,monthlyBalance:-12,production:4,inflation:1.2}},{id:'audit',label:'Najpierw audyt',text:'Ryzykujesz płace, ale nie podpisujesz czeku w ciemno.',state:{governmentCapacity:-2,constitutionalOrder:2},politics:{capital:1}},{id:'union',label:'Wezwij Dragicia i Velicia razem',text:'Przerzucasz kryzys na stół negocjacyjny.',memoryRequired:'m-dragic-seat',state:{constitutionalOrder:1},politics:{capital:2},followup:'dravina-table'}]},
{id:'dravina-table',title:'Stół w Dravinie',source:'KSP / SALA 4',body:'Dragić przychodzi z trzema przewodniczącymi zakładów. Velić przychodzi sam. Obaj wiedzą, że drugi ma dokumenty, których nie chce pokazać.',priority:88,minDay:2,once:true,condition:(_s,_p,seen)=>seen.includes('queue:dravina-table'),choices:[{id:'freeze',label:'Zamrozić zwolnienia na 30 dni',text:'Związek dostaje oddech, zarząd czas.',state:{unemployment:-.2,monthlyBalance:-5},politics:{capital:1}},{id:'books',label:'Wymusić otwarcie ksiąg',text:'Konflikt z Veliciem, ale państwo dostaje dane.',state:{governmentCapacity:2},politics:{capital:2}},{id:'walk',label:'Niech dogadają się sami',text:'KSP nie bierze odpowiedzialności.',state:{constitutionalOrder:-2}}]},
{id:'karsko-march',title:'Marsz w Karsku',source:'WOJEWODA / KARSKO',body:'Około osiem tysięcy ludzi idzie pod Zgromadzenie. Na razie pokojowo. Młodzi autonomiści żądają publikacji pełnego Układu Karskiego i gwarancji transferów.',priority:85,minDay:3,once:true,condition:(s,p)=>s.regions.karsko.unrest>55&&!has(p,'m-beran-autonomy'),choices:[{id:'confirm',label:'Potwierdź Układ publicznie',text:'Stolica wiąże sobie ręce, ale odbiera paliwo radykałom.',state:{constitutionalOrder:4},politics:{capital:1,mandates:4}},{id:'silence',label:'Nie reaguj',text:'Demonstracja pozostaje problemem Berana.',state:{constitutionalOrder:-2,mediaTemperature:4}},{id:'police',label:'Wzmocnij ochronę urzędów',text:'Bez zakazu marszu. Więcej policji, więcej kamer.',state:{security:3,mediaTemperature:3,constitutionalOrder:-1}}]},
{id:'currency-rumor',title:'Plotka o dewaluacji',source:'BANK CENTRALNY / PILNE',body:'W kantorach w Veligradzie ustawia się kolejka. „Jutro” pyta bank centralny o rzekomą trzydziestoprocentową dewaluację. Milić twierdzi, że ktoś testuje odporność rynku.',priority:82,minDay:3,once:true,condition:(s)=>s.reserves<1800||s.currency<100,choices:[{id:'sell',label:'Sprzedaj 120 mln rezerw',text:'Bronisz kursu natychmiast.',state:{reserves:-120,currency:5,inflation:-.7}},{id:'brief',label:'Daj mediom twarde dane',text:'Ryzykujesz pytania o strukturę rezerw.',state:{mediaTemperature:-5,constitutionalOrder:2}},{id:'pavelic',label:'Użyj kanału Pavelić',text:'Kontrolowany przeciek przez „Jutro”.',memoryRequired:'m-pavelic-brief',state:{mediaTemperature:-8},politics:{capital:1}}]},
{id:'army-letter',title:'List siedemnastu pułkowników',source:'SZTAB GENERALNY / POUFNE',body:'Do generała Radicia trafia list oficerów żądających „jednoznacznej ochrony jedności państwa”. Nie ma wezwania do zamachu. Jest sugestia, że politycy tracą kontrolę.',priority:78,minDay:5,once:true,condition:(s)=>s.constitutionalOrder<58,choices:[{id:'ignore',label:'Pozostaw sprawę Radiciowi',text:'Armia rozwiązuje problem wewnętrznie.',state:{armyReadiness:1}},{id:'meeting',label:'Wezwij Radicia',text:'Cywilna władza pokazuje zainteresowanie bez publicznego alarmu.',state:{constitutionalOrder:2},politics:{capital:1}},{id:'publish',label:'Ujawnij list',text:'Przenosisz spór do opinii publicznej.',state:{mediaTemperature:9,constitutionalOrder:-3}}]},
{id:'files-leak',title:'Ktoś zna treść szarej koperty',source:'SŁUŻBA BEZPIECZEŃSTWA / TYLKO DO RĄK',body:'Savić twierdzi, że jeden z reporterów zna kryptonim operacji z materiałów przekazanych KSP. Pyta tylko: „Czy koperta opuściła pański gabinet?”.',priority:95,minDay:4,once:true,condition:(_s,p)=>has(p,'m-savic-sources'),choices:[{id:'investigate',label:'Wewnętrzne dochodzenie',text:'Sprawdzasz własny sekretariat.',state:{governmentCapacity:-2,security:2},politics:{capital:-1}},{id:'deny',label:'Zaprzecz i żądaj dowodów',text:'Nie przyznajesz Służbie prawa do kontroli KSP.',politics:{capital:1}},{id:'joint',label:'Wspólna cicha kontrola',text:'Dopuszczasz ludzi Savić do własnego obiegu dokumentów.',state:{security:4,constitutionalOrder:-1}}]}
];
export function nextEvent(s:StateSnapshot,p:PoliticalState,seen:string[]){return events.filter(e=>!seen.includes(e.id)&&s.day>=e.minDay&&(!e.maxDay||s.day<=e.maxDay)&&e.condition(s,p,seen)).sort((a,b)=>b.priority-a.priority)[0];}
export function applyEventChoice(s:StateSnapshot,p:PoliticalState,e:GameEvent,c:EventChoice){const ns={...s};for(const [k,v] of Object.entries(c.state??{})){if(typeof v==='number'&&typeof (ns as any)[k]==='number')(ns as any)[k]=Number(((ns as any)[k]+v).toFixed(1));}ns.day+=1;const np={...p,capital:p.capital+(c.politics?.capital??0),mandates:Math.max(0,Math.min(240,p.mandates+(c.politics?.mandates??0)))};return {state:ns,politics:np};}
