export type Bloc='prezydentura'|'rząd'|'parlament'|'kapitał'|'związki'|'bezpieczeństwo'|'regiony';
export type NPC={id:string;name:string;age:number;role:string;bloc:Bloc;region:string;publicFace:string;drive:string;fear:string;leverage:string;secret:string;traits:string[];trust:number;influence:number;relations:Record<string,number>};
export const npcs:NPC[]=[
{id:'varga',name:'Aleksandar Varga',age:61,role:'Prezydent Republiki',bloc:'prezydentura',region:'Veligrad',publicFace:'Ojciec konstytucji, chłodny legalista.',drive:'Zostawić po sobie państwo silniejsze od partii.',fear:'Upokorzenie urzędu i rozpad Karska.',leverage:'Weto, nominacje bezpieczeństwa, autorytet armii.',secret:'W 1991 obiecał Karsku szerszą autonomię fiskalną; zapis istnieje w jednym prywatnym protokole.',traits:['cierpliwy','pamiętliwy','formalista'],trust:48,influence:92,relations:{markovic:-35,koren:24,radic:18,beran:-10}},
{id:'markovic',name:'Irena Marković',age:47,role:'Premier',bloc:'rząd',region:'Veligrad',publicFace:'Ekonomistka reform, technokratka bez sentymentu.',drive:'Dokończyć reformę gospodarczą przed kolejnymi wyborami.',fear:'Hiperinflacja i przejęcie reform przez oligarchów.',leverage:'Administracja, budżet, młodzi wiceministrowie.',secret:'Jej gabinet ukrył skalę złych kredytów dwóch banków państwowych, by uniknąć paniki.',traits:['pracowita','ostra','transakcyjna'],trust:42,influence:84,relations:{varga:-35,stojan:28,velic:-42,koren:-5}},
{id:'koren',name:'Milan Koren',age:55,role:'Przewodniczący Zgromadzenia',bloc:'parlament',region:'Morava',publicFace:'Mistrz procedury i kompromisu.',drive:'Uczynić parlament centrum nowego systemu.',fear:'Przedterminowe wybory, które zniszczą jego partię.',leverage:'Kalendarz ustaw, komisje, kontakty między klubami.',secret:'Utrzymuje dyskretny kanał z prezydentem mimo publicznej neutralności.',traits:['ugodowy','sprytny','ostrożny'],trust:53,influence:74,relations:{varga:24,markovic:5,beran:15,dragic:-18}},
{id:'stojan',name:'Petar Stojan',age:39,role:'Minister finansów',bloc:'rząd',region:'Primorje',publicFace:'Młody jastrząb fiskalny.',drive:'Ustabilizować walutę nawet kosztem recesji.',fear:'Druk pieniądza i polityczne ratowanie każdego kombinatu.',leverage:'Dostęp do danych budżetu i negocjacji z wierzycielami.',secret:'Prowadzi nieformalną sondę z zagranicznym funduszem w sprawie sprzedaży części Velmashu.',traits:['analityczny','ambitny','niecierpliwy'],trust:45,influence:61,relations:{markovic:28,velic:-55,novak:12}},
{id:'velic',name:'Boris Velić',age:58,role:'Dyrektor holdingu Velmash',bloc:'kapitał',region:'Dravina',publicFace:'Patriarcha przemysłu ciężkiego.',drive:'Ocalić holding i własną sieć wpływu.',fear:'Audyt kredytów i rozbicie przedsiębiorstwa.',leverage:'63 tys. miejsc pracy, lokalni dyrektorzy, bank przemysłowy.',secret:'Velmash płaci fikcyjnym spółkom pośredniczącym w Primorju; część pieniędzy wraca do polityki.',traits:['towarzyski','bezwzględny','hojny'],trust:31,influence:79,relations:{markovic:-42,stojan:-55,dragic:38,milic:22}},
{id:'dragic',name:'Jovan Dragić',age:50,role:'Przewodniczący Federacji Metalowców',bloc:'związki',region:'Dravina',publicFace:'Twardy negocjator robotniczy.',drive:'Nie dopuścić do terapii szokowej kosztem Draviny.',fear:'Utrata kontroli nad radykalnym skrzydłem związku.',leverage:'Strajki, rady zakładowe, ulica.',secret:'Wie o księgowych nadużyciach Velmashu, ale milczy, bo ujawnienie może zabić zakład.',traits:['lojalny','gniewny','pragmatyczny'],trust:37,influence:72,relations:{velic:38,koren:-18,markovic:-30}},
{id:'radic',name:'Gen. Luka Radić',age:63,role:'Szef Sztabu Generalnego',bloc:'bezpieczeństwo',region:'Rudnik',publicFace:'Stary profesjonalista, armia poza polityką.',drive:'Utrzymać jedność armii i granic.',fear:'Wciągnięcie wojska w walkę partyjną.',leverage:'Korpus oficerski i realna kontrola mobilizacji.',secret:'Odrzucił nieformalną prośbę prezydentury o przygotowanie planu ochrony instytucji w stolicy.',traits:['zdyscyplinowany','konserwatywny','honorowy'],trust:56,influence:86,relations:{varga:18,savic:-12,radovan:8}},
{id:'savic',name:'Mira Savić',age:44,role:'Dyrektorka Służby Bezpieczeństwa Państwa',bloc:'bezpieczeństwo',region:'Veligrad',publicFace:'Niewidoczna urzędniczka nowej republiki.',drive:'Zachować zdolność państwa do widzenia zagrożeń.',fear:'Rozbicie służby na partyjne frakcje.',leverage:'Akta, podsłuchy sądowe, kadry z poprzedniego systemu.',secret:'Część archiwum z lat 80. została skopiowana przed zmianą ustroju i znajduje się poza oficjalną ewidencją.',traits:['cicha','precyzyjna','nieufna'],trust:40,influence:82,relations:{radic:-12,varga:5,pavelic:-25}},
{id:'beran',name:'Tomas Beran',age:46,role:'Przewodniczący Zgromadzenia Karska',bloc:'regiony',region:'Karsko',publicFace:'Umiarkowany autonomista.',drive:'Wyciągnąć realne gwarancje dla regionu bez wojny ze stolicą.',fear:'Radykalizacja młodych i interwencja służb.',leverage:'Regionalny parlament, policja komunalna, kontakty w Ostrovii.',secret:'Rozmawia z Ostrovią o awaryjnym finansowaniu szkół, ale odrzucił ofertę wsparcia politycznego.',traits:['cierpliwy','lokalny patriota','elastyczny'],trust:49,influence:71,relations:{varga:-10,koren:15,radovan:-35}},
{id:'radovan',name:'Ilija Radovan',age:33,role:'Lider Ruchu Jedności Narodowej',bloc:'parlament',region:'Rudnik',publicFace:'Telewizyjny trybun nowej prawicy.',drive:'Zbudować masowy ruch na kryzysie starej elity.',fear:'Normalizacja sytuacji przed wyborami.',leverage:'Wiecowa mobilizacja, radio, młodzi działacze.',secret:'Jego kampanię częściowo finansuje sieć importerów z Primorja.',traits:['charyzmatyczny','ryzykancki','mściwy'],trust:18,influence:58,relations:{beran:-35,radic:8,pavelic:30}},
{id:'pavelic',name:'Vesna Pavelić',age:36,role:'Właścicielka dziennika „Jutro”',bloc:'kapitał',region:'Primorje',publicFace:'Symbol nowych niezależnych mediów.',drive:'Zbudować imperium medialne zanim rynek zostanie podzielony.',fear:'Przejęcie przez banki lub kompromitacja źródeł.',leverage:'Największy dziennik prywatny i sieć reporterów.',secret:'Płaci za przecieki z administracji; jedno ze źródeł jest bardzo blisko KSP.',traits:['ciekawska','odważna','cyniczna'],trust:29,influence:65,relations:{savic:-25,radovan:30,markovic:10}},
{id:'milic',name:'Davor Milić',age:52,role:'Prezes Banku Centralnego',bloc:'rząd',region:'Veligrad',publicFace:'Spokojny strażnik waluty.',drive:'Ocalić rezerwy i niezależność banku.',fear:'Run na walutę po ujawnieniu bilansów bankowych.',leverage:'Stopy, dewizy, informacje o przepływach.',secret:'Rezerwy płynne są o 210 mln niższe niż oficjalna liczba z powodu zastawionych aktywów.',traits:['powściągliwy','techniczny','uparty'],trust:50,influence:76,relations:{velic:22,stojan:14,markovic:16}}
];
export const blocLabels:Record<Bloc,string>={prezydentura:'Prezydentura',rząd:'Rząd i administracja',parlament:'Parlament',kapitał:'Holdingi, banki i media',związki:'Związki zawodowe',bezpieczeństwo:'Bezpieczeństwo i armia',regiony:'Regiony'};
