export type Memory={id:string;personId:string;kind:'favor'|'debt'|'promise'|'grievance'|'leverage';label:string;value:number;day:number};
export type PoliticalState={capital:number;appointments:number;mandates:number;memories:Memory[];trust:Record<string,number>;respect:Record<string,number>;fear:Record<string,number>};
export const initialPolitics:PoliticalState={capital:5,appointments:2,mandates:96,memories:[],trust:{},respect:{},fear:{}};
export type Offer={id:string;personId:string;title:string;ask:string;price:string;response:string;capital:number;mandates:number;trust:number;respect:number;fear:number;memory:Omit<Memory,'day'>};
export const offers:Offer[]=[
{id:'varga-karsko',personId:'varga',title:'Kanał prezydencki',ask:'Prezydent poprze 120-dniowe pełnomocnictwa KSP, jeśli Sekretarz zagwarantuje, że żadna nowa umowa z Karskiem nie zostanie podpisana bez opinii jego kancelarii.',price:'Oddajesz część swobody w sprawie Karska.',response:'Varga nie gratuluje. Prosi sekretarza, by zanotował jedno zdanie: „Państwo nie może mieć dwóch polityk terytorialnych”.',capital:2,mandates:12,trust:8,respect:4,fear:0,memory:{id:'m-varga-karsko',personId:'varga',kind:'promise',label:'Konsultacja z prezydentem przed nową umową z Karskiem',value:8}},
{id:'markovic-budget',personId:'markovic',title:'Pakiet stabilizacyjny',ask:'Premier odda KSP kontrolę nad międzyresortowym zespołem kryzysowym. W zamian oczekuje publicznego poparcia zamrożenia części wydatków.',price:'Wchodzisz w spór rządu ze związkami i regionami.',response:'Marković przesuwa teczkę bez uśmiechu. „Dobrze. Teraz zobaczymy, czy umie pan powiedzieć nie także komuś innemu niż ministrowi”.',capital:2,mandates:5,trust:7,respect:7,fear:0,memory:{id:'m-markovic-cuts',personId:'markovic',kind:'debt',label:'KSP poparł pakiet oszczędnościowy premier',value:7}},
{id:'koren-vote',personId:'koren',title:'Większość proceduralna',ask:'Koren może dostarczyć głosy do pilnych uchwał KSP. Chce gwarancji, że każda nadzwyczajna kompetencja wygaśnie automatycznie po 120 dniach.',price:'Blokujesz możliwość cichego przedłużenia uprawnień.',response:'Koren podaje rękę. „Jeżeli wszystko pójdzie dobrze, za cztery miesiące obaj będziemy mniej ważni. To jest warunek, nie wada”.',capital:1,mandates:24,trust:10,respect:5,fear:-2,memory:{id:'m-koren-sunset',personId:'koren',kind:'promise',label:'Automatyczne wygaśnięcie pełnomocnictw KSP po 120 dniach',value:10}},
{id:'velic-jobs',personId:'velic',title:'Dravina za spokój',ask:'Velić zatrzyma presję dyrektorów na strajk solidarnościowy, jeśli KSP pomoże uruchomić linię płynności dla Velmashu.',price:'Powstaje polityczny dług wobec człowieka z toksyczną księgowością.',response:'Velić nalewa koniak, którego nie zamawiałeś. „Nie ratuje pan mnie. Ratuje pan sześćdziesiąt trzy tysiące wypłat. Proszę o tym pamiętać”.',capital:3,mandates:3,trust:5,respect:8,fear:0,memory:{id:'m-velic-credit',personId:'velic',kind:'favor',label:'Nieformalna obietnica pomocy płynnościowej dla Velmashu',value:9}},
{id:'dragic-truce',personId:'dragic',title:'Siedem dni ciszy',ask:'Dragić odroczy strajk generalny o tydzień. Żąda osobistego miejsca przy stole rozmów o restrukturyzacji Velmashu.',price:'Legitymizujesz związek jako współdecydenta gospodarczego.',response:'Dragić patrzy długo. „Siedem dni. Ósmego albo siedzimy przy stole, albo stoimy przed bramą”.',capital:2,mandates:6,trust:8,respect:6,fear:1,memory:{id:'m-dragic-seat',personId:'dragic',kind:'promise',label:'Miejsce Federacji Metalowców przy negocjacjach Velmashu',value:8}},
{id:'savic-files',personId:'savic',title:'Dostęp specjalny',ask:'Savić udostępni KSP wybrane materiały operacyjne o przepływach pieniędzy przez San Varo. Chce pisemnej ochrony źródeł i zakazu przekazania surowych akt prokuraturze.',price:'Przyjmujesz informacje, których pochodzenia nie będziesz mógł ujawnić.',response:'Savić zostawia cienką szarą kopertę. „Jeżeli kiedykolwiek zobaczę jej kopię w sądzie, następna koperta nie trafi tutaj”.',capital:2,mandates:0,trust:6,respect:5,fear:3,memory:{id:'m-savic-sources',personId:'savic',kind:'promise',label:'Ochrona źródeł Służby w materiałach przekazanych KSP',value:9}},
{id:'beran-guarantee',personId:'beran',title:'Gwarancja dla Karska',ask:'Beran publicznie odrzuci postulaty secesyjne, jeśli KSP potwierdzi ciągłość Układu Karskiego i transferów regionalnych.',price:'Budżet i prezydentura dostają ograniczone pole manewru.',response:'Beran poprawia okulary. „Nie proszę o prezent. Proszę, żeby państwo wykonywało własny podpis”.',capital:2,mandates:8,trust:10,respect:4,fear:-1,memory:{id:'m-beran-autonomy',personId:'beran',kind:'promise',label:'KSP potwierdził ciągłość Układu Karskiego i transferów',value:10}},
{id:'pavelic-media',personId:'pavelic',title:'Kontrolowany przeciek',ask:'Pavelić opublikuje tekst uspokajający rynek, jeśli dostanie ekskluzywny briefing o stanie rezerw bez prawa cytowania źródła.',price:'Dajesz prywatnym mediom uprzywilejowany dostęp do informacji państwowej.',response:'Pavelić zamyka notes. „Nie jestem pańskim biuletynem. Ale jeżeli liczby się zgadzają, historia sama będzie spokojniejsza”.',capital:1,mandates:0,trust:5,respect:7,fear:0,memory:{id:'m-pavelic-brief',personId:'pavelic',kind:'favor',label:'Ekskluzywny briefing KSP dla „Jutra”',value:5}}
];
export function acceptOffer(p:PoliticalState,o:Offer,day:number):PoliticalState{const bump=(r:Record<string,number>,id:string,v:number)=>({...r,[id]:(r[id]??0)+v});return {...p,capital:p.capital+o.capital,mandates:Math.min(240,p.mandates+o.mandates),trust:bump(p.trust,o.personId,o.trust),respect:bump(p.respect,o.personId,o.respect),fear:bump(p.fear,o.personId,o.fear),memories:[{...o.memory,day},...p.memories]};}
