export type StateSnapshot={day:number;treasury:number;monthlyBalance:number;reserves:number;inflation:number;unemployment:number;debt:number;currency:number;production:number;food:number;energy:number;constitutionalOrder:number;governmentCapacity:number;security:number;armyReadiness:number;mediaTemperature:number;parliamentSupport:number;regions:Record<string,{stability:number;prosperity:number;unrest:number}>};
export const initialState:StateSnapshot={day:1,treasury:620,monthlyBalance:-118,reserves:1840,inflation:31.7,unemployment:11.4,debt:46,currency:100,production:71,food:83,energy:64,constitutionalOrder:54,governmentCapacity:47,security:62,armyReadiness:67,mediaTemperature:58,parliamentSupport:96,regions:{capital:{stability:58,prosperity:72,unrest:31},dravina:{stability:43,prosperity:49,unrest:68},karsko:{stability:39,prosperity:55,unrest:61},morava:{stability:64,prosperity:46,unrest:28},primorje:{stability:61,prosperity:68,unrest:25},rudnik:{stability:52,prosperity:31,unrest:44}}};
export type StateAction={id:string;label:string;detail:string;effects:Partial<StateSnapshot>;regional?:{id:string;stability?:number;prosperity?:number;unrest?:number}};
export const stateActions:StateAction[]=[
{id:'fx',label:'Bronić kursu franka',detail:'Bank centralny sprzedaje 90 mln ₣ rezerw. Kurs uspokaja się, ale bufor dewizowy maleje.',effects:{reserves:-90,currency:4,inflation:-1.1,constitutionalOrder:1}},
{id:'liquidity',label:'Awaryjna płynność dla przemysłu',detail:'120 mln ₣ kredytu pomostowego przez banki państwowe. Produkcja i zatrudnienie dostają oddech; rośnie presja cenowa i fiskalna.',effects:{treasury:-35,monthlyBalance:-12,production:4,unemployment:-.6,inflation:1.3},regional:{id:'dravina',stability:7,prosperity:4,unrest:-9}},
{id:'cuts',label:'Zamrozić wydatki dyskrecjonalne',detail:'Ministerstwa tracą część limitów. Deficyt spada, administracja zwalnia, regiony czują zaciskanie pasa.',effects:{monthlyBalance:38,governmentCapacity:-5,constitutionalOrder:-1},regional:{id:'rudnik',stability:-4,prosperity:-2,unrest:5}},
{id:'fuel',label:'Subwencja paliwowa dla rolnictwa',detail:'Tymczasowe dopłaty stabilizują dostawy żywności i Moravę, lecz pogarszają saldo budżetu.',effects:{treasury:-22,monthlyBalance:-9,food:6,inflation:-.4},regional:{id:'morava',stability:5,prosperity:3,unrest:-6}},
{id:'security',label:'Podnieść gotowość bezpieczeństwa',detail:'Dodatkowe patrole, dyżury i ochrona infrastruktury. Aparat jest sprawniejszy, ale atmosfera polityczna gęstnieje.',effects:{treasury:-8,security:7,governmentCapacity:-1,mediaTemperature:5,constitutionalOrder:-2}},
{id:'army',label:'Utrzymać armię w koszarach',detail:'Rozkaz potwierdza apolityczność wojska. Gotowość kryzysowa lekko spada, legitymizacja konstytucyjna rośnie.',effects:{armyReadiness:-3,constitutionalOrder:5,security:-1}}
];
export function applyAction(s:StateSnapshot,a:StateAction):StateSnapshot{const n={...s,regions:{...s.regions}} as StateSnapshot;for(const [k,v] of Object.entries(a.effects)){if(typeof v==='number') (n as any)[k]=Number(((n as any)[k]+v).toFixed(1));}if(a.regional){const r={...n.regions[a.regional.id]};for(const k of ['stability','prosperity','unrest'] as const){const v=a.regional[k];if(typeof v==='number')r[k]=Math.max(0,Math.min(100,r[k]+v));}n.regions[a.regional.id]=r;}n.day+=1;return n;}
export const stateGroups=[{name:'FINANSE',keys:[['treasury','Gotówka budżetu','mln ₣'],['monthlyBalance','Saldo miesięczne','mln ₣'],['reserves','Rezerwy dewizowe','mln ₣'],['debt','Dług publiczny','% PKB']]},{name:'GOSPODARKA',keys:[['inflation','Inflacja','% r/r'],['unemployment','Bezrobocie','%'],['currency','Indeks franka',''],['production','Produkcja','/100'],['food','Bezpieczeństwo żywności','/100'],['energy','Bezpieczeństwo energii','/100']]},{name:'PAŃSTWO',keys:[['constitutionalOrder','Ład konstytucyjny','/100'],['governmentCapacity','Sprawność administracji','/100'],['security','Bezpieczeństwo','/100'],['armyReadiness','Gotowość armii','/100'],['mediaTemperature','Temperatura mediów','/100'],['parliamentSupport','Mandaty skłonne poprzeć KSP','/240']]}] as const;
