import {useMemo,useState} from 'react';
import {regions,headlines} from './game/world';
import {npcs,blocLabels,NPC} from './game/people';
import {initialState,stateActions,stateGroups,applyAction,StateSnapshot} from './game/state';
import {initialPolitics,offers,acceptOffer,PoliticalState} from './game/politics';
import {nextEvent,applyEventChoice,GameEvent} from './game/events';
type Tab='biurko'|'kryzysy'|'państwo'|'polityka'|'mapa'|'ludzie'|'archiwum';
export default function App(){
 const [tab,setTab]=useState<Tab>('biurko');const [selected,setSelected]=useState(regions[0]);const [person,setPerson]=useState<NPC>(npcs[0]);const [filter,setFilter]=useState('wszyscy');const [state,setState]=useState<StateSnapshot>(initialState);const [politics,setPolitics]=useState<PoliticalState>(initialPolitics);const [log,setLog]=useState<string[]>([]);const [reply,setReply]=useState('');const [seen,setSeen]=useState<string[]>([]);const [eventLog,setEventLog]=useState<string[]>([]);
 const visible=useMemo(()=>filter==='wszyscy'?npcs:npcs.filter(n=>n.bloc===filter),[filter]);const current=nextEvent(state,politics,seen);const regionState=state.regions[selected.id];
 const act=(id:string)=>{const a=stateActions.find(x=>x.id===id)!;setState(s=>applyAction(s,a));setLog(l=>[a.label,...l].slice(0,6));};
 const deal=(id:string)=>{const o=offers.find(x=>x.id===id)!;if(politics.memories.some(m=>m.id===o.memory.id))return;setPolitics(p=>acceptOffer(p,o,state.day));setReply(o.response);setPerson(npcs.find(n=>n.id===o.personId)!);};
 const choose=(e:GameEvent,id:string)=>{const c=e.choices.find(x=>x.id===id)!;if(c.memoryRequired&&!politics.memories.some(m=>m.id===c.memoryRequired))return;const r=applyEventChoice(state,politics,e,c);setState(r.state);setPolitics(r.politics);setSeen(x=>[...x,e.id,...(c.followup?['queue:'+c.followup]:[])]);setEventLog(x=>[`${e.title} — ${c.label}`,...x].slice(0,8));};
 return <div className="shell"><header><div><b>INTERREGNUM</b><span> REPUBLIKA VELIGRADU</span></div><div className="date">{2+state.day} STYCZNIA 1994 · 07:40</div></header><nav>{(['biurko','kryzysy','państwo','polityka','mapa','ludzie','archiwum'] as Tab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x.toUpperCase()}{x==='kryzysy'&&current?' · !':''}</button>)}</nav>
 {tab==='biurko'&&<main className="desk"><section className="brief"><div className="stamp">ŚCIŚLE TAJNE</div><p className="kicker">KOMITET STABILIZACJI PAŃSTWA · BIULETYN 001</p><h1>Państwo działa.<br/>Na razie.</h1><p>Od sześciu tygodni Republika Veligradu nie ma rządu posiadającego pewność większości. Prezydent odmawia podpisania trzech nominacji. Premier twierdzi, że prezydent przekracza konstytucję. Bank centralny traci rezerwy. Dravina grozi strajkiem. Karsko pyta, czy stolica nadal przestrzega umowy autonomicznej.</p><p>Wczoraj o 23:18 parlament powołał <strong>Komitet Stabilizacji Państwa</strong>. Twój urząd miał być sekretariatem technicznym. O 06:12 na biurko trafiły jednak trzy teczki oznaczone „decyzja Sekretarza”.</p><div className="signature">SEKRETARIAT KSP / EGZ. 1</div></section><aside><h3>STAN PAŃSTWA</h3><div className="metric"><span>Rezerwy</span><b>{state.reserves} mln ₣</b></div><div className="metric"><span>Inflacja</span><b>{state.inflation}%</b></div><div className="metric"><span>Kapitał polityczny</span><b>{politics.capital}</b></div><div className="metric"><span>Mandaty skłonne poprzeć KSP</span><b>{politics.mandates}/240</b></div>{current&&<><h3>PILNE</h3><p className="warning">{current.title}</p></>}<h3>TELEKS</h3>{headlines.map((h,i)=><p className="wire" key={h}><em>0{7+i}:2{i}</em> {h}</p>)}</aside></main>}
 {tab==='kryzysy'&&<main className="crisis"><section><p className="kicker">SYSTEM ZDARZEŃ / PRIORYTET OPERACYJNY</p><h1>Kryzysy</h1>{current?<article className="eventpaper"><div className="eventhead"><span>{current.source}</span><b>PRIORYTET {current.priority}</b></div><h2>{current.title}</h2><p>{current.body}</p><div className="choices">{current.choices.map(c=>{const locked=!!c.memoryRequired&&!politics.memories.some(m=>m.id===c.memoryRequired);return <button key={c.id} disabled={locked} onClick={()=>choose(current,c.id)}><b>{c.label}</b><span>{c.text}</span>{locked&&<em>WYMAGA WCZEŚNIEJSZEGO ZOBOWIĄZANIA / KONTAKTU</em>}</button>})}</div></article>:<div className="quiet"><h2>Brak spraw wymagających natychmiastowej decyzji.</h2><p>Wykonuj decyzje państwowe i polityczne. Warunki świata uruchamiają kolejne zdarzenia.</p></div>}</section><aside><p className="kicker">KRONIKA DECYZJI</p>{eventLog.length?eventLog.map((x,i)=><p className="log" key={i}>D-{state.day-i} / {x}</p>):<p className="muted">Historia kampanii dopiero się zaczyna.</p>}<p className="classified">EVENTY NIE SĄ LOSOWYMI OKNAMI. MAJĄ WARUNKI, PRIORYTETY, JEDNORAZOWOŚĆ I ŁAŃCUCHY. CZĘŚĆ OPCJI ISTNIEJE TYLKO, JEŚLI WCZEŚNIEJ ZBUDOWAŁEŚ ODPOWIEDNIĄ RELACJĘ.</p></aside></main>}
 {tab==='państwo'&&<main className="stateview"><section><p className="kicker">CENTRUM OPERACYJNE KSP · DZIEŃ {state.day}</p><h1>Stan państwa</h1><div className="stategrid">{stateGroups.map(g=><div className="statebox" key={g.name}><h3>{g.name}</h3>{g.keys.map(([key,label,unit])=><div className="statrow" key={key}><span>{label}</span><b>{(state as any)[key]} {unit}</b></div>)}</div>)}</div><h2>Decyzje wykonawcze</h2><div className="actions">{stateActions.map(a=><button key={a.id} onClick={()=>act(a.id)}><b>{a.label}</b><span>{a.detail}</span></button>)}</div></section><aside><p className="kicker">DZIENNIK OPERACYJNY</p>{log.length?log.map((x,i)=><p className="log" key={i}>D-{state.day-i} / {x}</p>):<p className="muted">Brak decyzji.</p>}</aside></main>}
 {tab==='polityka'&&<main className="politics"><section><p className="kicker">GABINET SEKRETARZA · ROZMOWY NIEPROTOKOŁOWANE</p><h1>Polityka</h1><div className="politicaltop"><div><b>{politics.capital}</b><small>KAPITAŁ POLITYCZNY</small></div><div><b>{politics.mandates}</b><small>MANDATY / 240</small></div><div><b>{politics.memories.length}</b><small>AKTYWNE ZOBOWIĄZANIA</small></div></div><h2>Oferty na stole</h2><div className="dealgrid">{offers.map(o=>{const n=npcs.find(x=>x.id===o.personId)!;const done=politics.memories.some(m=>m.id===o.memory.id);return <article className={done?'deal done':'deal'} key={o.id}><p className="kicker">{n.name} · {n.role}</p><h3>{o.title}</h3><p>{o.ask}</p><div className="price"><b>CENA:</b> {o.price}</div><button disabled={done} onClick={()=>deal(o.id)}>{done?'UZGODNIONO':'PRZYJMIJ WARUNKI'}</button></article>})}</div></section><aside><p className="kicker">PAMIĘĆ POLITYCZNA</p>{reply&&<div className="reply">{reply}</div>}{politics.memories.map(m=><div className="memory" key={m.id}><b>{m.kind.toUpperCase()}</b><span>{m.label}</span></div>)}</aside></main>}
 {tab==='mapa'&&<main className="mapview"><section><p className="kicker">PODZIAŁ ADMINISTRACYJNY / 1994</p><h1>Republika Veligradu</h1><div className="regions">{regions.map(r=><button key={r.id} onClick={()=>setSelected(r)} className={selected.id===r.id?'selected':''}><b>{r.name}</b><small>{r.subtitle}</small></button>)}</div></section><aside><p className="kicker">DOSSIER REGIONU</p><h2>{selected.name}</h2><p>{selected.subtitle} · {selected.population}</p><div className="bar"><i style={{width:(regionState?.stability??selected.stability)+'%'}}/></div><small>STABILNOŚĆ {regionState?.stability??selected.stability}/100</small><div className="bar"><i style={{width:(regionState?.prosperity??selected.prosperity)+'%'}}/></div><small>PROSPERITY {regionState?.prosperity??selected.prosperity}/100</small>{regionState&&<><div className="bar"><i style={{width:regionState.unrest+'%'}}/></div><small>NAPIĘCIE {regionState.unrest}/100</small></>}<p>{selected.note}</p></aside></main>}
 {tab==='ludzie'&&<main className="people"><section><p className="kicker">KARTOTEKA KSP · DOSTĘP SEKRETARZA</p><h1>Ośrodki siły</h1><div className="filters"><button className={filter==='wszyscy'?'selected':''} onClick={()=>setFilter('wszyscy')}>WSZYSCY</button>{Object.entries(blocLabels).map(([k,v])=><button key={k} className={filter===k?'selected':''} onClick={()=>setFilter(k)}>{v}</button>)}</div><div className="cards">{visible.map(n=><button key={n.id} className={'personcard '+(person.id===n.id?'selected':'')} onClick={()=>setPerson(n)}><span className="initials">{n.name.split(' ').map(x=>x[0]).join('')}</span><div><b>{n.name}</b><small>{n.role}</small><em>{blocLabels[n.bloc]}</em></div><strong>{n.influence}</strong></button>)}</div></section><aside className="dossier"><p className="kicker">DOSSIER / {person.id.toUpperCase()}</p><h2>{person.name}</h2><p className="role">{person.age} lat · {person.role} · {person.region}</p><p className="quote">„{person.publicFace}”</p><div className="tripstat"><div><b>{person.trust+(politics.trust[person.id]??0)}</b><small>ZAUFANIE</small></div><div><b>{politics.respect[person.id]??0}</b><small>SZACUNEK</small></div><div><b>{politics.fear[person.id]??0}</b><small>OBAWA</small></div></div><dl><dt>DĄŻY DO</dt><dd>{person.drive}</dd><dt>OBAWIA SIĘ</dt><dd>{person.fear}</dd><dt>DŹWIGNIA</dt><dd>{person.leverage}</dd></dl></aside></main>}
 {tab==='archiwum'&&<main className="archive"><p className="kicker">ARCHIWUM PAŃSTWOWE</p><h1>1945—1994</h1>{[['1945','Powstaje Republika Ludowa Veligradu.'],['1962','Reforma przedsiębiorstw.'],['1974','Układ Karski.'],['1983','Kryzys zadłużeniowy.'],['1989','Koniec monopolu partii.'],['1991','Konstytucja kompromisu.'],['1993','Pęknięcie koalicji reform.'],['1994','INTERREGNUM.']].map(([y,t])=><article key={y}><b>{y}</b><p>{t}</p></article>)}</main>}<footer>TURA 5 BUILD · EVENT ENGINE · v0.5.0</footer></div>
}
